apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-eeem
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-eeem
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-eeem
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-eeem
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-eeem
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pxjn-tenant/rhtap-demo-app/hacbs-test-project-eeem@sha256:75d0715536bca7446b64ff703abd4d2c7a2480e69f408365e1c3c7073f4b9526
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
