apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-eeem
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pxjn-tenant/rhtap-demo-app/hacbs-test-project-eeem@sha256:e00c958a2b5422387ba6deb0fc6cf73c312f8d24761b599da06330e0711c1cbe
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
